### ISSUE TITLE
aktuelle Rundenanzahl im Manager neben der angewählten Paarung anzeigen

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#15]
Ich mach das mal stellvertretend auf:

Zur Zeit wird die Rundenanzahl in der Leiste bei den Partien angezeigt. Sobald man aber bei den Partien etwas nach unten scrollt, ist diese Information dann nicht mehr sichtbar. Mittlerweile haben wir aufgrund der hohen Teilnehmerzahlen fast immer mehr Partien, als auf einem Desktop angezeigt werden können. Daher muss zwangsläufig gescrollt werden.

Es wäre toll, wenn die aktuelle Rundenanzahl im Manager oben neben der aktuellen Partie angezeigt werden würde. Rechts neben der aktivierten Partie ist viel Platz für eine kleine Infozelle. (Da könnte man sogar über weitere Informationen nachdenken: Anzahl aller Partien, Anzahl ausstehender Partien, o.ä.).

**Comment by GoppeltM** [comment]
Irgendwie ist das in Vergessenheit geraten...
Was mache ich denn im Falle Playoffs, wo es mehrere "Runden" gleichzeitig gibt? Am besten immer die Runde der gewählten Partie anzeigen, oder? Ist ne kleinere Änderung, ich nehms mal mit niedriger Priorität auf
