### ISSUE TITLE
Größe des Speichers für Startnummer anpassen 

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#16]
Die Spielernummer einiger Spieler im Click-TT ist größer als 2147483647. Daher stürzt das Programm ab, wenn diese Spieler im click-TT erfasst wurden und die xml dann den PPC-Manager importiert wird.
Wir brauchen mehr bits.

**Comment by GoppeltM** [comment]
Das DTD Schema von Click-TT schweigt sich leider darüber aus was konkret hier erwartet wird, aber wir benutzen die Lizenznummer als letztes Sortierkriterium, müssen es also irgendwann mal zu einer Zahl machen (und nicht z.B. als String belassen). Deshalb wäre ein Typus wie Decimal wahrscheinlich plausibel. Ist nur die Frage was das für Nebenwirkungen hat, dass muss ich mir mal im Detail irgendwann angucken...
