### ISSUE TITLE
Rundenzahlen auf allen Ausdrucken

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#20]
Auf allen Ausdrucken steht ja oben die aktuelle Rundenzahl. Für unsere Ausdrucke passt diese Zahl allerdings leider nicht. 
Wäre es möglich, die Rundenzahl auf allen Aushängen um eins zu verringern? Das betrifft also das Ranking, die Ergebnisse und die neuen Partien.

**Comment by hartmutseiter** [comment]
Auch dieser Mangel ist mir aus früheren Jahren nicht bekannt. Ich glaube, das wäre uns früher schon aufgefallen.
