### ISSUE TITLE
Aktivierung der ersten Partie nach Rundenwechsel

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#22]
Nach dem klicken auf die „nächste Runde“ scheint die erste Begegnung nicht anwählbar zu sein. Man muss zuerst auf eine andere Partie klicken und dann zurück wechseln.

**Comment by hartmutseiter** [comment]
Kam einmal vor, dass das erste zu erfassende Ergebnis auf die erste angezeigte Partie fiel.

**Comment by FloEKa** [comment]
Also dann muss ich sagen - das ist doch hoffentlich verschmerzbar...
Dann warten wir halt auf das zweite Ergebnis derselben Klasse bevor wir dann dieses eintragen.

Auch hier denke ich: Aufwand, den Bug zu beseitigen und tatsächlicher Nutzen stehen in keinem Verhältnis...

**Comment by nkappler** [comment]
#36 war ein Duplikat hiervon

**Comment by nkappler** [comment]
> Auch hier denke ich: Aufwand, den Bug zu beseitigen und tatsächlicher Nutzen stehen in keinem Verhältnis...

War eine Zeile Code 😉
