### ISSUE TITLE
Ranking im Excel-Export ist nicht genauso sortiert, wie das Ranking im Ausdruck

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#23]
Die Protokolle in Excel sind nicht so sortiert, wie das Ranking. Das sorgt für Probleme beim Wechsel in die Playoffs.

**Comment by hartmutseiter** [comment]
Bei diesem Punkt bin ich etwas irritiert. Ich nutze die Daten aus "sp_rd07" seit deren Einführung (vor 2 oder 3 Jahren?) unkontrolliert als Input für meine PlayOff-Excel-Schnittstelle, und glaube nicht, in der Vergangenheit auf Mängel gestoßen zu sein.

**Comment by nkappler** [comment]
Dieses Problem konnte ich nicht reproduzieren, bei mir stimmt die Sortierung.
Bitte überprüfen, ob das Problem noch auftritt und falls ja bitte mir die XML schicken.

**Comment by nkappler** [comment]
Hallo, ich hatte endlich Zeit mir das anzuschauen. Das war echt eine harte Nuss muss ich zugeben.
Der Excel-Export funktioniert fehlerfrei, zumindest manchmal 😀 
Es gibt einen kleinen Haken, aber der lässt sich leicht umgehen...

<hr>

### Ein Beispiel:
Wir haben ein Turnier mit 7 Runden, nachdem alle Partien gespielt sind, wollen wir eine neue Runde starten,
aber das Programm wirft einen Fehler weil es die letzte Runde war und wird beendet.
Wir starten nun das Programm erneut, laden die Turnierdatei und exportieren die Rangliste als PDF.
Hierbei werden alle Punkte gezählt, inklusive der abgeschlossenen - im Programm aber nicht beendeten - Runde 7.
Wenn wir jetzt jedoch die Rangliste als Excel exportieren, wird der Turnierstand zu Beginn von Runde 7 genommen.
Die Partien von Runde 7 werden also nicht berücksichtigt.

### Um dieses Problem zu umgehen kann man nun die Playoffs starten, dann sind Excel und PDF wieder konsistent.

Generell scheinen PDF und Excel nur zu Beginn einer neuen Runde übereinzustimmen.
Hier scheinen mehrere kleinere Fehler beim Verwalten des internen Turnierzustands zusammenzuwirken und machen die Sache etwas undurchsichtig.

Ich gehe davon aus, dass die Punkteberechnung insgesamt stimmt und werde zumindest einen kleinen Patch vorbereiten,
damit das Programm sich nicht selbst beendet, wenn keine neuen Runden mehr gestartet werden können.
Außerdem will ich versuchen, die Freilose auch in der Gegnerbilanz aufzuführen, da es für diese ja auch einen Punkt gibt, dies sollte zu mehr Transparenz bei der Punkteberechnung führen.

<hr>

Auch die Live-Liste ist nicht ganz konsistent, bzw. nicht 100% live.
Wenn man zB. ein neues Turnier beginnt, haben alle Spieler zunächst 0 Punkte, bis Runde 1 abgeschlossen und Runde 2 gestartet wird. 
Beendete Partien aus Runde 1 werden während Runde 1 nicht in der Punktetabelle berücksichtigt.
Wenn man nun aber Runde 2 wieder verwirft, bleiben die ausgerechneten Punkte in der Tabelle stehen, lediglich die Buchholzpunkte werden zurückgesetzt, jedoch auch nur bei den Gewinnern der letzten Runde.

Diese Fehler wirken sich soweit ich das beurteilen kann nur auf die Anzeige aus. Da bei jedem Export und jeder Aktualisierung die Punkte neu berechnet werden und lediglich die Partien abgespeichert werden, scheint der Punktestand letztendlich immer korrekt zu sein, auch wenn er im Programm (und scheinbar im Excel) nicht immer aktuell angezeigt wird.

<hr>

Abschließend will ich sagen, dass dieser Bug erheblich mehr Aufmerksamkeit erfordert, um ihn final zu fixen. Es wäre hilfreich, wenn dieser Bereich möglichst genau getestet und dabei jeder einzelne Schritt dokumentiert würde, sodass man das Problem besser verstehen und reproduzieren kann.
