### ISSUE TITLE
Bug rund um die "nicht anwesenden" und "ausgeschiedenen" Spieler

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#26]
- „nicht anwesende Spieler“ werden unnötigerweise auf dem Ranking-Ausdruck aufgeführt (unten angehängt). 
- "ausgeschiedene Spieler" werden nicht angezeigt, obwohl das sinnvoll wäre.
- Nach dem Ausscheiden eines Spielers waren plötzlich alle "nicht anwesenden" Spieler wieder aktiviert, wurden wie alle anderen Aktiven gepaart und auf dem Ranking ausgedruckt, waren aber nicht in der Liveliste im Manager sichtbar.

Der letzte Punkt trat erst nach einem "Runde zurücknehmen" und anschließendem "Ausscheiden lassen" auf. Ein Zusammenhang wäre eventuell möglich.

**Comment by hartmutseiter** [comment]
Anmerkung hierzu. Auch in der B-Klasse hatten wir die Kombination "nicht anwesnder Spieler" und "ausgeschiedener Spieler". Einziger Unterschied zur A-Klasse: "Runde zurücknehmen" kam in der B-Klasse nicht zum Zuge.

**Comment by hartmutseiter** [comment]
Zur Überbrückung der supportfreien Zeit glaube ich das Risiko eines Wiederauftretens des Bugs dadurch mindern zu können, dass ich mittels Zerlegen der Turnierteilnehmer.xml in einzelne xml's für A-Klasse, B-Klasse, C-Klasse, D-Klasse, JA-Klasse, JB-Klasse zunächst den Zugriff mehrerer Programminstanzen auf ein und dieselbe Daten-XML verhindere. Oben beschriebene Zerlegung habe ich am vergangenen Wochenende erfolgreich mit einem geeigneten XML-Editor (Beyond Compare) durchgeführt. Turnierverlauf war an beiden Tagen störungsfrei.

**Comment by GoppeltM** [comment]
Die Entscheidung alles in einer XML zuu speichern, war ursprünglich dazu gedacht, einen reibungsloseren Import und Export in Click-TT zu ermöglichen.
Außerdem sollte so verhindert werden, dass ein Turnier auseinander gerissen werden kann, indem z.B. manche Dateien verschoben werden, und manche nicht.

Aber heute sieht es rh so aus, dass ohne Nachbearbeitung kein Import möglich ist. Wenn es der Robustheit dient, könnte ein aufteilen hilfreich sein.

**Comment by nkappler** [comment]
Nach ausgiebiger Analyse der XML Datei, bzw was PPCM nach jedem Schritt abspeichert, habe ich das Problem isoliert und auch eine kürzere Methode gefunden, den Bug
zu reproduzieren:

**1. XML mit StartlistenEditor generieren und in PPCM öffnen,
2. Runde 1 starten.
3. Speichern und Programm schließen. (Ergebnispflege nicht nötig)
4. Programm erneut starten
5. Runde 1 verwerfen.
6. Runde 1 erneut starten, nun sind auch ausgeschiedene Spieler in der Matchauflistung.**

Während dem Turnier einen Spieler zu entfernen, bzw. dass das Zurücksetzen einer Runde manchmal nicht funktioniert, hat erstmal nichts damit zu tun.
Das Problem ist der Neustart des Programms währen eines laufenden Turniers.
Im Grunde "vergisst" PPCM in welcher Runde ein Spieler ausgeschieden ist, weil die ausgeschiedenen Spieler immer an der aktuellsten Runde hängen.
PPCM merkt sich zwar während es läuft, seit wann ein Spieler ausgeschieden ist, daher funktioniert das zurückdrehen von Runden anfänglich, aber diese
Information wird nie abgespeichert und durch den Neustart wird die Liste der ausgeschiedenen Spieler beim zurückdrehen einer Runde gelöscht.

<details>
Startlisteneditor legt matches Knoten mit inaktiven Spielern (Group 0) an.

PPC Manager:

-> Erstmaliges öffnen der XML -> Speichern:
Satzdifferenz, Gewinnsätze, SonnebornBerger & namespace Attribute werden an competition Knoten angehängt
NS wird von inactive Player zu Matches umgehängt

-> Nächste Runde (Runde 1) -> Speichern
Inactive Player Group wird hochgezählt -> sollte wohl eher dupliziert werden, damit gespeichert ist, WANN der Spieler ausgeschieden ist.
Jedes Match der Runde wird als Knoten im XML angelegt

[-> Runde verwerfen -> Speichern
Match Knoten werden entfernt
Group des InactivePlayers wird wieder runtergezählt, PPCM weiß also noch, dass er in der Runde zuvor bereits ausgeschieden war. 
  Diese Information existiert aber nur während das Programm läuft.

-> Nächste Runde -> Speichern
XML ist (abgesehen von den Zeitstempeln) wieder identisch zum ersten Mal als Runde 1 gestartet wurde.
] diese zwei Schritte sind optional und können beliebig oft ausgeführt werden

-> Programm schließen
Der ausgeschiedene Spieler gehört nun zu Runde 1, beim erneuten Start von PPCM weiß das Programm nicht mehr, dass der Spieler von Anfang an
ausgeschieden war. Dies trifft auch auf während den Runden ausgeschiedenen Spielern zu.

-> Programm erneut starten
wenn jetzt gespeichert wird, wird interessanterweise das group Attribut des ausgeschiedenen Spielers wieder auf 0 gesetzt (vielleicht auch zurückgedreht),
allerdings macht es keinen Unterschied, der Bug tritt ab jetzt in jedem Fall auf.

-> Runde zurücksetzen -> Speichern
Match Knoten werden wie erwartet entfernt
InaktivePlayer Knoten wird fälschlicherweise auch entfernt, damit denkt PPCM, dass es keine abwesenden Spieler gibt, da das "abwesend" Attribut an anderer Stelle
im XML gepflegt wird und im Grunde von PPCM komplett ignoriert wird. Wie es scheint wird damit nur der Zustand der Checkboxen im 
StartlistenEditor persistiert.

Wenn nun eine neue Runde gestartet wird, oder aktiv ist werden alle Spieler bei der Matchkalkulation verwendet.
</details>

**Comment by GoppeltM** [comment]
>... . Im Grunde "vergisst" PPCM in welcher Runde ein Spieler ausgeschieden ist, weil die ausgeschiedenen Spieler immer an der aktuellsten Runde hängen. PPCM merkt sich zwar während es läuft, seit wann ein Spieler ausgeschieden ist, daher funktioniert das zurückdrehen von Runden anfänglich, aber diese Information wird nie abgespeichert und durch den Neustart wird die Liste der ausgeschiedenen Spieler beim zurückdrehen einer Runde gelöscht.


Danke für den Hinweis! Ich bin leider grad sehr unter Wasser, aber das ist ein eindeutiger Hinweis. So sollte sich das per Test reproduzieren lassen.
