### ISSUE TITLE
Diskussion: Gegnerprofil

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#27]
Beim Gegnerprofil gibt es derzeit mehrere Baustellen:

Bugs:
- Im Ausdruck wird bei jedem Spieler nur die letzte Partie dargestellt - nicht alle Partien.

Erfahrungswerte mit dem Gegnerprofil:
- Turnierteilnehmer verstehen das Profil nicht (Start-ID + "G" für "gewonnen" bzw. "V" für "verloren")
- Turnierteilnehmer nutzen ID zum suchen des Gegners nicht
- In der Praxis suchen die Teilnehmer ihre Infos auf den Ergebnislisten der vergangenen Runden

Diskussion:
Alle o.g. Punkte legen nahe, auf das Gegnerprofil auf dem Ranking zu verzichten. Vorteile wären, dass wir weniger Papier benötigen, da dann alle Informationen zu einem Spieler in ein Zeile im Hochformat passen und dass die o.g. Bugs nicht beseitigt werden müssen.
Problem: Was ist, wenn wir tatsächlich mal namensgleiche Spieler in einem Klassement haben sollten? Klassementübergreifend hatten wir diesen Fall sogar schon.

**Comment by hartmutseiter** [comment]
Das provoziert die Idee, mit den Namen auch den Verein anzudrucken

**Comment by GoppeltM** [comment]
Ich hab für den einen Bug mit der Drucksicht ein eigenes Issue aufgemacht und verschoben, siehe #32

**Comment by FloEKa** [comment]
@hartmutseiter: Du meinst dann aber allen Drucken, auf denen wir den Namen bislang als primäre Info nutzen? Da fallen mir ein: 1. "Ranking", 2. "Schiedsrichterzettel", 3. "Ergebnisse letzte Runde", 4. "Partien nächste Runde"

1. Auf dem Ranking steht der Vereinsname ja bereits. 
2. Am Design der Schiedsrichterzettel haben wir jetzt schon so lange rumgemacht - Tobi wünscht gerade, dass der Name kleiner gemacht wird, damit lange Doppelnamen auch lesbar sind. Der Vereinsname würde wieder extrem viel Platz einnehmen.
4. Ein Kompromissvorschlag: Wir ergänzen den Verein noch auf den "Partien der nächsten Runde".  Die Vorteile wären:
1. Der Platz dafür ist da, weil die ganze Breite einer DIN-A4-Seite durch zwei Spieler nie gebraucht wird. 
2. Wenn wir tatsächlich denn Fall haben, dass mal zwei Spieler desselben Namens in einer Klasse spielen können unsere Mädels, die die Partien aufrufen  auf diese Liste zurückgreifen - weil Hartmut sie ja unkompliziert einmal mehr ausdrucken kann (Die Mädels managen das zurzeit immer mit Kopien der Schiedsrichterzettel).

@GoppeltM: Wie gesagt - warte da erst einmal mit einem Fix (#32). Vielleicht beschließen wir ja, das Gegnerprofil vom Ausdruck komplett zu entfernen. Ich wäre aus o.g. Gründen dafür!
Wie ist dazu euer Votum? Hartmut? Tobi?
