### ISSUE TITLE
Mehr Variabilität für die Ausdrucke

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#3]
Gegenwärtig ist aus dem Manager heraus ja ein Druck auf Rundenanfang damit verbunden, dass ein Exemplar der (neuen) Partien und eines der Schiedsrichterzettel herauskommt. Im Verlauf hat sich aber gezeigt, dass unsere Mikrofonmädels besser mit dem Partienzettel arbeiten können, daher bräuchten wir diesen eigentlich dreimal und die Schiedsrichterzettel nur einmal.
Vorschlag: Kann man das noch individualisieren? Also eine eigene variable Einstellung für die Anzahl der Ausdrucke einrichten. Auch gerne über eine Configdatei - das muss nicht unbedingt im System selber sein. Im Übrigen gilt das eigentlich auch für die anderen beiden Ausdrucke (Ranking und Ergebnisse). Es kam vor, dass wir doch gerne noch einmal eine Kopie des Rankings für uns an der Turnierleitung ausdrucken wollten und dann kam immer noch die Ergebnisliste als Müll dazu.

Da jetzt ja ständig live berechnet wird könnten wir doch theoretisch mit zwei Schaltflächen auskommen - unabhängig von Rundenende oder -Anfang.
1. Ranking drucken. (Zeitpunkt natürlich am Ende einer Runde vor dem "neu paaren")
2. Paarungen drucken. 
(2.1 Ergebnisse drucken --> Am Ende vor dem "neu paaren")
(2.2 Neue Paarungen drucken --> Am Anfang direkt nach dem "neu paaren")

**Comment by FloEKa** [comment]
Okay, beim Turnier 2015 war diese Sache noch immer ein Thema. Aktuell ist es so gelöst:

Beim Klick auf "Rundenende" werden automatisch in einem Druckauftrag die Ergebnisse und das Ranking ausgedruckt. Das ist mittlerweile ungeschickt. Wir brauchen die Ergebnisse möglichst im Hochformat, die Liste im Querformat.

Beim Klick auf "Rundenanfang" werden automatisch die neuen Paarungen und die Schiedsrichterzettel ausgedruckt. Das ist mittlerweile ungeschickt, da wir die Paarungen am besten dreimal und die Schiedsrichterzettel nur einmal brauchen.

Ergo: Format und Anzahl sollten für alle vier Ausdrucke individuell einstellbar sein. Wenn das technisch machbar wäre, wäre es super, da eine Art Voreinstellung für zu entwerfen, die sich das System dann merkt. Idealerweise sollten diese Einstellungen aber je nach Bedarf auch während des Turniers flexibel angepasst werden können.

Zur Not wäre es natürlich auch denkbar, für alle vier Seiten je einen Druckdialog öffnen zu lassen, in welchem dann die Einstellungen getätigt werden können. Bei drei Wettbewerben mit je sechs Runden erzeugt das allerdings dann viel rumgeklicke in solchen Druckdialogen. Daher plädiere ich für doe oben genannte Option, wenn die technisch machbar ist.

**Comment by GoppeltM** [comment]
Nachdem das Thema ja neue Priorität gewonnen hat, fasse ich nochmal zusammen:
Es geht vor allem um Anzahl und Orientierung des Drucks. Während z.B. die Rangliste nach jedem Rundenende an mehreren Stellen im Raum aufgehängt wird, braucht es die Schiri Zettel nur einmalig. Außerdem wird regelmäßig viel Papier verdruckt bis die richtige Einstellung gefunden wurde.

Mögliche Lösungsansätze die mir dazu in den Kopf schießen, sind:
- Ich mache eine Druck-Optionen Seite, auf der ich für jede einzelne Drucksicht einen eigenen Druckdialog einblende, und die daraus resultierenden Einstellungen anschließend speichere
- Ich puffere den Druck quasi zwischen, d.h. bei Beginn einer neuen Runde könnte ich immer noch den Abschluss der Vorrunde im Speicher halten, oder umgekehrt. Vielleicht kann ich damit gleich auch #6 behandeln.
- Ich mache eine Druckvorschau, indem ich das Dokument in einem eigenen Fenster vergleichbarer Größe hoste. Ist aber möglicherweise aufwendiger umzusetzen.

**Comment by GoppeltM** [comment]
Ich hab jetzt alles umgesetzt bis auf die Druckvorschau, ist im aktuellen Release drin. Ich warte erstmal auf euer Feedback, mache den Issue dann zu, und mach dann evtl. bei Bedarf ein weiteres Issue für eine Druckvorschau auf.

**Comment by GoppeltM** [comment]
Feedback war bisher positiv, deshalb mache ich jetzt zu.
