### ISSUE TITLE
Schiedrichterzettel: Name dann Vorname sowohl auf Monitor als auch auf Ausdruck 

### ISSUE THREAD

**Issue by hartmutseiter** [GoppeltM/PPC-Manager#30]
Ich (Tobias) habe am Wochenende mal wieder Ergebnisse eintragen dürfen. Der PPC Manager ist offen, ich sehe alle Paarungen der laufenden Runde vor mir. Manchmal musste ich etwas suchen, bis ich die entsprechende Paarung gefunden habe, die ich gerade eintragen will. Denn auf meinem Schiedsrichterzettel steht Name, Vorname und im PPC Manager steht dann Vorname Nachname. Hier würde ich es begrüßen, wenn hier wie auf den Schiedsrichterzetteln, Name Vorname zu sehen wäre. (Mangel von Tobias gemeldet)

**Comment by nkappler** [comment]
Soweit ich das beurteilen kann, ist das bereits erledigt worden.

Falls hier doch noch etwas offen sein sollte, bitte den Bug wieder aufmachen und etwas detaillierter beschreiben, wie das gewünschte Layout sein soll...

![grafik](https://user-images.githubusercontent.com/9429273/184545771-05a9daab-d0d4-43a4-b3e6-9e827ab5cf5a.png)
