### ISSUE TITLE
Format person licence-nr nicht kompatibel mit ClickTT

### ISSUE THREAD

**Issue by hartmutseiter** [GoppeltM/PPC-Manager#35]
Teilnehmer des vergangenen Wochenendes besaßen erstmals alphanumerische Licence-nr bzw. ein Teilnehmer die Licence-nr = "00000000". Beide lassen die Speicherung einer Anwesenheit mittels des Startlisteneditiors nicht zu. Für beide Konstellationen muss gegenwärtig mittels Manipulation der Licence.nr innerhalb der XML-Datei eine vorübergehende Kompatibilität mit der Turniersoftware hergestellt werden. Am Ende vor dem Datenimport ins ClickTT müssen diese Änderungen wieder rückabgewickelt werden.

**Comment by GoppeltM** [comment]
Die Lizenznummer ist aktuell eine 64Bit Zahl.
Wenn ich mich richtig erinnere, haben wir diese als letztes Sortierkriterium drin, mit dem Gedanken dass bei sonstiger Gleichheit Stammspieler weiter oben geführt werden sollten.
Aber bei dem Wust an unterschiedlichen Lizenznummern die wir bisher gesehen haben, ist die Regel mittlerweile absurd.
Ich sehe zwei Wege: Lizenznummer als Text werten, und als solchen alphabetisch sortieren, oder Lizenznummer als Text werten, und als Text alphabetisch sortieren.

So oder so zeigt sich: Lizenznummern sind nicht zwangsläufig Zahlen, und evtl. auch nicht eindeutig (00000...). Ergo eine miese Wahl als Primärschlüssel.
