### ISSUE TITLE
Begegnungsfeld ist leer bei Beginn einer neuen Runde

### ISSUE THREAD

**Issue by nkappler** [GoppeltM/PPC-Manager#36]
Beim Beginn einer neuen Runde ist das UI zum erfassen der Ergebnisse inaktiv, obwohl die erste Begegnung ausgewählt ist.
Man muss zuerst eine andere Begegnung auswählen, dann wieder die erste Begegnung auswählen, um diese bearbeiten zu können.

**Comment by GoppeltM** [comment]
Da es unwahrscheinlich ist dass man das erste Ergebnis auch als erstes einträgt, fällt das in der Praxis wenig ins Gewicht. Aber ja, sauberer wäre natürlich ne gescheite Initialisierung.
