### ISSUE TITLE
Excel Export fehlerhaft?

### ISSUE THREAD

**Issue by nkappler** [GoppeltM/PPC-Manager#37]
![grafik](https://user-images.githubusercontent.com/9429273/182032934-97c08675-2fc2-4d67-8264-867c4e3cce66.png)

Habe diese Stelle im Code beim Debuggen gefunden, meiner Meinung nach sollte `Skip(1)` erst nach `Reverse` aufgerufen werden, ansonsten wird die neueste Runde statt Runde 0 übersprungen.

Selbes Spiel bei den ausgeschiedenen Spielern... Muss das ganze noch genauer testen, daher lade ich das ganze hier als Gedächtnisstütze hoch...

**Comment by GoppeltM** [comment]
Iirc sind Spielrunden als Stack implementiert, und der gibt beim iterieren die obersten Elemente zuerst raus. Aber vielleicht ist es auch ein Bug

**Comment by nkappler** [comment]
> und der gibt beim iterieren die obersten Elemente zuerst raus.

Ganz genau, die "oberste" Runde ist die jüngste Runde, Runde 0 ist ganz unten im Stack und ich denke diese soll übersprungen werden.

**Comment by GoppeltM** [comment]
Hm. Ich glaube das ist drin, damit im Excel Export die laufende Spielrunde nicht mit drin ist. Evtl. mit Hartmut abstimmen.

**Comment by nkappler** [comment]
@hartmutseiter weißt du da mehr dazu?

**Comment by nkappler** [comment]
fixed via 652a210
