### ISSUE TITLE
GitHub Contributor

### ISSUE THREAD

**Issue by nkappler** [GoppeltM/PPC-Manager#39]
Hi Marius,

könntest du mich bitte als Contributor im Projekt hinzufügen, dann kann ich Fixes selbst mergen und Patches/ neue Release erstellen.
Andernfalls müsste ich das auf meinem Fork fortführen, was auf Dauer umständlich sein kann...

Ich hab gerade noch einen Test gefixt, der nun mit dem geänderten Export funktioniert.
Außerdem habe ich die VS Erweiterung für Wix auf meinem Rechner eingerichtet und ein Patch-Release erstellt.

**Comment by GoppeltM** [comment]
Du bist jetzt schon ne ganze Weile als Collaborator hier eingetragen. Damit müsstest du eigentlich ausreichend Zugriff haben.

**Comment by nkappler** [comment]
stimmt, danke! 

Nach master mergen geht nur via PR wie ich sehe, kann ich das selbst machen, oder musst du die immer durchwinken?

**Comment by GoppeltM** [comment]
Ich hab jetzt die Branch Protection mal deaktiviert.

**Comment by nkappler** [comment]
alles klar, danke dir 😊
