### ISSUE TITLE
Formatierung des Rankings über mehrere Seiten bitte einheitlich

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#4]
Die Formatierung des Rankings auf der zweiten Seite kann von der auf der ersten Seite wegen der dynamischen Spaltenbreiten abweichen. Das sieht dann aber blöd aus, wenn wir die für den Aushang untereinander kleben.

**Comment by FloEKa** [comment]
Kann man diesen "Issue" wieder öffnen?

Das Problem besteht nach wie vor. Die Spaltenbreiten, werden nach wie vor für jede Seite anhand des jeweils längsten Eintrags unterschiedlich angepasst.

**Comment by GoppeltM** [comment]
Für mich selber als Notiz:
Der physikalische Drucker stößt offenbar ein erneutes UpdateLayout an, und überschreibt damit meine mühsam gehackten Werte.
Momentan sehe ich zwei Lösungswege:
1) ich versuche im Speicher ein XPS Document zu drucken, und dieses wiederum an den Drucker weiterzuleiten. Hat den Charme dass auf dem Drucker mit höherer Wahrscheinlichkeit das rauskommt was ich auch in der Druckvorschau sehe. Damit ist aber noch nicht garantiert dass der Hack auch in Zukunft funktioniert
2) Ich überlasse das Layout dem DataGrid, und scrolle es in den richtigen Bereich. Damit gehe ich an die Wurzel des Problems - aber scrollen ist ein bisschen hakelig. Wird schwierig zu vermeiden, dass man bestimmte Zeilen doppelt sieht.
Ich könnte versuchen, alle überflüssigen Zeilen entweder als Hidden oder Collapsed auszublenden - in der Hoffnung, dass sie trotzdem im Layouting berücksichtigt werden. (z.B. so: http://stackoverflow.com/questions/4728561/wpf-datagrid-hide-complete-row-through-databinding) Ist zwar auch schmutzig, scheint mir aber plausibler als die erste Lösung zu sein.

**Comment by GoppeltM** [comment]
Nach viel Rumprobiererei habe ich mich für Lösung 3) entschieden: ich rendere alle Zeilen in einem Grid, und verschiebe das Grid durch Translation.
Das wirft neue Probleme auf: es ist z.B. gar nicht so einfach, jetzt Kopf- und Fußzeilen zu rendern. Die muss ich erst wieder neu überdenken. Auch besteht momentan die Gefahr, dass einzelne Zeilen zerschnitten sind. Ich denke, die eleganteste Lösung wäre ein überschneidender Bereich. Viel Kleinkrams, aber die Marschrichtung ist richtig, denke ich.
