### ISSUE TITLE
Berechnung der Jahreszahlen bei den Jugendlichen anpassen

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#5]
Vorschlag: Das Programm bezieht aus dem Datum des PCs das aktuelle Jahr und berechnet daraus die drei Zeitfenster u18, u15, u13.
Stichtag ist der 1.1. eines bestimmten Jahres. Gelten muss dann folgende Berechnung:
u18: aktuelles Jahr - Geburtsjahr = 17 oder 16 oder 15
u15: aktuelles Jahr - Geburtsjahr = 14 oder 13
u13: aktuelles Jahr - Geburtsjahr = 12 bis 1

**Comment by GoppeltM** [comment]
Code sieht eigentlich gut aus. Bitte gegentesten, dann mach ich hier zu.
