### ISSUE TITLE
Wie verfahren wir mit dem Übergang aus der letzten Runde zu den Playoffs?

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#6]
Wenn die sechste Runde zu ende ist, wird es hektisch: Im Augenblick ist zusätzliches das Handling der Software zu diesem Zeitpunkt etwas kompliziert:

Zwei Dinge sind dabei zentral:
1. Wir brauchen ein Endklassement --> Druck auf den "Rundenende-Button"
2. Wir brauchen für die Excelmakros den Export der letzten Runde - dieser wird aber erst geschrieben, wenn die nächste Runde gepaart wird. In dem Fall wird aber wiederum die xml um überflüssige Daten ergänzt.

Vorschlag: Wäre es möglich einen extra Button einzufügen, der den aktuellen Stand in die excel-file ablegt (also je ein Tabellenblatt: Ranking und Ergebnisse nach dem bestehenden Format). Das wäre dann quasi die letzte Aktion im Manager. Danach kann er geschlossen werden, die xml ist "upload-fertig" und weiter gehts mit den Playoffs in excel.

**Comment by FloEKa** [comment]
Über diese Sache sind wir erneut gestolpert.
Ich meine, in der Konsequenz wurden die "leeren" Spielpaarungen der (nicht wirklich gespielten) siebten Runde für den Import auf click-TT manuell (!) aus der xml gelöscht.
Das ist sicher keine gute Lösung.

**Comment by GoppeltM** [comment]
Vielleicht sollte man darüber neu nachdenken, wann was geschrieben wird. Ich warte halt auf irgendein Ereignis was mir sagt: so, jetzt beginnt/endet eine Runde. Bisher nehme ich dazu nur den "nächste Runde" Knopf. Ich könnte aber auch ein Ereignis nehmen wie "Spielpartie abgeschlossen", oder aus Performance Gründen wahrscheinlich besser: "Alle Spielpartien abgeschlossen".
