### ISSUE TITLE
Bitte das Problem mit dem "Runde zurücknehmen" untersuchen.

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#7]
Wie bereits telefonisch besprochen. Der Button funktioniert nur dann korrekt, wenn alle Klassements gespeichert, geschlossen und das Betroffene neu eingelesen wurde. Das ist sehr aufwendig und fehleranfällig.

**Comment by GoppeltM** [comment]
Ich habe noch eine weitere Theorie wie das passieren konnte... der Startlisteneditor hat sich zu lange den Inhalt der XML gemerkt, und eventuell zu Zeitpunkten gespeichert in der der PPC Manager diese bereits verändert hatte. Einen Mischbetrieb aus beiden Programmen haben wir nie so richtig erprobt.
Ich habe jetzt die Zeit in der eine XML im Speicher bleibt deutlich reduziert, d.h. das sollte Zugriffsfehler deutlich unwahrscheinlicher machen. Hoffe, wir haben damit das Problem endgültig erschlagen.
