### ISSUE TITLE
Diskussionspunkt: Jugendklassement

### ISSUE THREAD

**Issue by FloEKa** [GoppeltM/PPC-Manager#9]
Der Diskussionspunkt ist ob wir eine neue Einteilung vornehmen und wenn ja, nach welchen Kriterien.
Im Grunde gibt es drei unterschiedliche Maßstäbe.

1. Aufteilung nach TTR  (also Jugend A und B oder A, B und C) 
2. Aufteilung nach Geschlecht (also m und w)
3. Aufteilung nach Alter (u18, u15 und u13)

Es kann nun natürlich jede Kombination geben.

Mein Vorschlag: wir machen drei Klassen: A, B und C und verzichten auf m + w.

Eventuell könnten wir ein "Bambini-Finale" zwischen den beiden (vier/acht) jüngsten Teilnehmern auszutragen, damit die wenigstens ne Urkunde mitnehmen dürfen. Da müssen wir aber mal die alten Ergebnisse danach durchforsten, ob sich die "Jüngsten" nicht schon auf sportlichem Weg für Playoff der anderen Klassen qualifizieren konnten.

**Comment by FloEKa** [comment]
Ich glaube, das hier kann zu. Wir haben eine Entscheidung getroffen.

**Comment by GoppeltM** [comment]
Für die Akten: die Anforderung hat sich schlicht überholt, und der Umgang mit den Jugendklassements war schon immer eher die Ausnahme von der Regel. Daher: geschlossen.
